### ISSUE TITLE
Rename this github repo to moodle-local_reminders

### ISSUE THREAD

**Issue by brendanheywood** [isuru89/moodle-local_reminders#100]
There is a well established pattern for the naming of repos for moodle plugins which is 'moodle-frankenstyle'. There is no downside to renaming a git repo, github gracefully manages redirects and still honors the old git urls for pulls so everything keeps working.

It should be located here:

https://github.com/isuru89/moodle-local_reminders

**Comment by isuru89** [comment]
Done. Thanks for letting me know.

**Comment by brendanheywood** [comment]
thanks for the quick response @isuru89 :)
