### ISSUE TITLE
Hardcoded string

### ISSUE THREAD

**Issue by dinism** [isuru89/moodle-local_reminders#105]
I'm a PT-PT Translator.

With a course in Portuguese, in the message sent there are a string hardcoded to english (OVERDUE):
![imagem](https://user-images.githubusercontent.com/14828021/110249122-74efcc00-7f6c-11eb-9073-10f0ba921864.png)
Can the string in bottom of image (Moodle Calendar) be translated?

**Comment by isuru89** [comment]
@dinism Thank you for reporting this issue. This will be fixed in the next release very soon.

**Comment by isuru89** [comment]
This has been fixed and released with plugin version 2.2.4. @dinism 
https://moodle.org/plugins/pluginversions.php?plugin=local_reminders
