### ISSUE TITLE
Cron error: Argument 1 passed to message_send() must be an instance

### ISSUE THREAD

**Issue by Carlos-mb** [isuru89/moodle-local_reminders#111]
Hello

I'm very noob with moodle and I'm having this error in cron execution: 

Excepción - Argument 1 passed to message_send() must be an instance of core\message\message, instance of stdClass given, called in [dirroot]/local/reminders/lib.php on line 432 !!!

I guess I should have redacted a message, but I don't know where. 

The main problem is that this error stops the cron execution and its creating other problems in my site. I have had to disable the plugin to let cron jobs work properly. 

I'll thank any help.

Regards,
Carlos.

**Comment by isuru89** [comment]
@Carlos-mb It is better if you can specify which Moodle version and plugin version is being used in your environment. I feel like there is a mismatch between this plugin and the moodle core api.

**Comment by Carlos-mb** [comment]
I thank your answer, I finally uninstalled the plugin that causes the error.

I think it was a plugin to send reminders for next events... but I can't tell you more because this issue happened one month ago.

Now, the site is working fine and I'll not install this plugin again. 

Regards,
