### ISSUE TITLE
Enable / disable reminder plugin on course (activity) level

### ISSUE THREAD

**Issue by msd-hftm** [isuru89/moodle-local_reminders#130]
At the moment, there exists only a global enable / disable option (Administrator -> Plugins -> Local Plugins -> Reminders section). Enabling the reminder e-mails only if a Moodle course teacher / user has the explicitly wish would be very nice.

**Comment by isuru89** [comment]
@msd-hftm 
This feature has been released with plugin v2.4 today.

To enable this feature:
  1. Moodle admin needs to check 'Explicit Reminder Activation` and then by default, new events will not be sent unless teachers enable them on the course reminder page explicitly.

Note: However, remember that this will not affect to the already existing events and reminders
