### ISSUE TITLE
How to rename this "Reminder from Moodle Calendar"

### ISSUE THREAD

**Issue by harismateen** [isuru89/moodle-local_reminders#135]
Hi,
How to rename this?
Reminder from Moodle Calendar

![image](https://user-images.githubusercontent.com/38554929/133933569-0fde82d6-d24d-44a6-9250-695a6435b286.png)

**Comment by isuru89** [comment]
@harismateen 
Currently, this is not customizable from plugin settings, but until such enhancement is provided, you can modify https://github.com/isuru89/moodle-local_reminders/blob/master/lang/en/local_reminders.php#L99 in your moodle installation (if you have access to the installation)

I'll provide an input box in plugin settings in the next version.

Thanks for your feedback.

**Comment by isuru89** [comment]
This will be implemented with #137 feature

**Comment by isuru89** [comment]
@harismateen this has been released with plugin v2.5
