### ISSUE TITLE
Error from cron. ++ Did you remember to make the first column something unique in your call to get_records? Duplicate value '4' found in column 'id'. ++

### ISSUE THREAD

**Issue by sat-igor** [isuru89/moodle-local_reminders#136]
Execute scheduled task: Local Reminders (local_reminders\task\send_reminders)
... started 18:02:03. Current memory use 53.3Мбайт.
   [Local Reminder] Time window: пятница, 17 Сентябрь 2021, 17:47 to пятница, 17 Сентябрь 2021, 18:02
   [Local Reminder] Found 1 upcoming events. Continuing...
   [Local Reminder] Processing event in ahead of 1 days.
   [Local Reminder] Processing event#53 [Type: open, inaheadof=1 days]...
   [Local Reminder] Finding out users for event#53...
++ Did you remember to make the first column something unique in your call to get_records? Duplicate value '4' found in column 'id'. ++
* line 1282 of \lib\dml\mysqli_native_moodle_database.php: call to debugging()
* line 4060 of \lib\accesslib.php: call to mysqli_native_moodle_database->get_records_sql()
* line 696 of \local\reminders\locallib.php: call to get_role_users()
* line 298 of \local\reminders\locallib.php: call to get_active_role_users()
* line 354 of \local\reminders\locallib.php: call to handle_course_activity_event()
* line 296 of \local\reminders\lib.php: call to process_activity_event()
* line 99 of \local\reminders\lib.php: call to local_reminders_cron_pre()
* line 48 of \local\reminders\classes\task\send_reminders.php: call to local_reminders_cron_task()
* line 253 of \lib\cronlib.php: call to local_reminders\task\send_reminders->execute()
* line 120 of \lib\cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of \lib\cronlib.php: call to cron_run_scheduled_tasks()
* line 81 of \admin\cron.php: call to cron_run()
  [Local Reminder] Starting sending reminders for 53 [type: open, mod: quiz]
  
  **This function makes a dubble id in param - fields - 'ra.id, u.*'**
  
  /**
 * Returns array of users active (not suspended) in the provided contexts and
 * at the same time belongs to the given roles.
 *
 * @param array $activityroleids role ids
 * @param object $context context to search for users
 * @return array of user records
 */
function get_active_role_users($activityroleids, $context) {
    return get_role_users($activityroleids, $context, true, 'ra.id, u.*',
                    null, false, '', '', '',
                    'ue.status = :userenrolstatus',
                    array('userenrolstatus' => ENROL_USER_ACTIVE));
}

**Comment by sat-igor** [comment]
Moodle 3.11.2+ (Build: 20210820)

**Comment by isuru89** [comment]
@sat-igor hmm... it seems this works fine in older versions. Something must have been changed in the newer version of Moodle, which I yet to release a plugin version.

Let me recreate it and provide a fix in next immediate version.

Thanks for reporting!

**Comment by isuru89** [comment]
This is fixed with plugin v2.5
