### ISSUE TITLE
Description of event for group activity reminders missing in email message

### ISSUE THREAD

**Issue by ligockym** [isuru89/moodle-local_reminders#150]
**Describe the bug (required)**
The reminder notification for group event in calendar does not include event description, but only name of activity. 

**To Reproduce (required)**
1. Set reminder notification when an event is created. 
2. Create new event in calendar for a group in a course (where you are as member) with description.
3. Check email message in your email client, there is no description from event, but instead of description, there is a title of the event.

**Expected behavior (required)**
Description of event should be visible in email message that is sent. 

**Temporary solution**
I changed line in file group_reminder.class.php to take description from event, because it seems that `$formattercls` is null. 

 https://github.com/isuru89/moodle-local_reminders/blob/1572e2029fccdb3cac05032d6e7815ba67b5d732/contents/group_reminder.class.php#L182 

into: 
```$description = isset($formattercls) ? $formattercls->get_description($this->activityobj, $this->event) : $this->event->description;```

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/8171427/159534691-8e555f8f-925a-4b8e-b9c6-1e9fcf0e580f.png)

**Comment by ligockym** [comment]
Possibly connected to https://github.com/isuru89/moodle-local_reminders/issues/109

**Comment by isuru89** [comment]
@ligockym Good catch! Thanks for reporting.

Will include this in the next immediate version.

**Comment by isuru89** [comment]
Fixed with plugin v2.6
