### ISSUE TITLE
Decouple activity start from activity end reminders 

### ISSUE THREAD

**Issue by JoMeX20** [isuru89/moodle-local_reminders#151]
**This is an enhancement. (required)**

**It has no relation to a third-party module in Moodle (required)**

**This enhancement should supports moodle versions 3.5 or above. (required)**

**Problem description. (required)**
Currently the reminder setting for the start and the end of an activity is coupled. In our case we use three reminders 16, 7 and 1 day before an activity (quiz) ends. That is not useful for the actvity start because multiple reminders annoying the course participants. It would be sufficient if an activity start will be announced once e.g. 1 day/hour/minute before or directly at the start time.

**Solution (required)**
Decouple activity start from activity end reminders by 
 - remove the selection field "local_reminders_duesend" or set it to activity end so the reminders are only related to activity end 
 - add local_reminders_duerdays and local_reminders_duecustom for activity start

**Comment by isuru89** [comment]
Fixed with plugin release v2.6.

Introduced two new settings to control activity openings. One is for setting ahead of days for reminders, and the other is for controlling opening events on the course reminders page.

**Comment by JoMeX20** [comment]
Thanks a lot Isuru to implement decoupling of activity start reminders from activity end reminders in revision v2.6!
Obviously there is still a small error in the implementation. Reminders for activity start periods are sent only if the reminders for activity end periods are set. E.g. it is not possible to have a start reminder 3 days before if the end reminder 3 days is deactivated. You can see it on the course reminders settings page: only the start period check boxes are selectable that are selected as end period in the global event reminder settings.
