### ISSUE TITLE
Activity reminders for Zoom not working

### ISSUE THREAD

**Issue by louisaoc** [isuru89/moodle-local_reminders#158]
On Moodle 3.11.x and Zoom plugin v4.6.0 the Zoom activity reminders do not work.
Our other activities work as well as BigBlueButton.

I also turned on the explicit option and the activity isn't even listing on the course reminder page.

**To Reproduce**
1. Set the plugin setting to activity reminders on and ensure Zoom is not excluded.
2. Set it to a 1-day reminder local_reminders_dueopenrdays and for local_reminders_duerdays
3. Set explicit reminder on
4. Go to a course and create a zoom activity with a date of about 25hours+ in future from now
5. Ensure you use an enrolled student if your setting is on student role only
6. Depending on cron frequency, check for mail until 24hr mark

**Expected behavior**
Expect to receive the reminder email.

We investigated (since other web conferencing tool activity reminders work) and since the date-time in Moodle for Zoom is not called open or due, I thought this is the issue and seems it is. Other activities' dates are called either open or due or close. Zoom does not have this type.
Our initial investigation is documented here: https://github.com/isuru89/moodle-local_reminders/discussions/157

**Comment by isuru89** [comment]
I implemented filter of these events from exclusion side. Now, zoom or any third-party events should be picked up automatically for overdue reminders.
