### ISSUE TITLE
Plugin uses user preference timezone rather than server timezone.

### ISSUE THREAD

**Issue by doiphode** [isuru89/moodle-local_reminders#159]
The reminders use user's preference for timezone to send out notifications.

This creates an issue if the user is using GMT rather than BST.

**Comment by isuru89** [comment]
Thanks for the suggestion.
Will include the changes in next release.

**Comment by isuru89** [comment]
@doiphode Would you kindly change the destination branch of the pull request to `release_2.0`. because, regression is done there.

**Comment by doiphode** [comment]
@isuru89 I have created a new pull request (#161) as per your suggestion.

**Comment by isuru89** [comment]
Released with plugin v2.7

**Comment by doiphode** [comment]
Thanks very much!
