### ISSUE TITLE
Plugin for moodle v4 .1

### ISSUE THREAD

**Issue by deesonlee** [isuru89/moodle-local_reminders#169]
Is there a version of this plugin compatible with Moodle 4.1, looking at https://moodle.org/plugins/local_reminders there doesn't seem to be a release marked as compatible yet.

Page says;
```
Release 2.7
Moodle 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 4.0
```

**Comment by deesonlee** [comment]
@isuru89 is there a release marked as compatible with Moodle 4.1?

**Comment by isuru89** [comment]
supported with plugin v2.7.1
