### ISSUE TITLE
Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by emilioferreiro** [isuru89/moodle-local_reminders#170]
**Bug:**
Occasionally, users receive the same email reminder 9 to 11 times. It usually happens with site events in the calendar.

**To Reproduce:**
The behavior is very random. It usually happen with site events, but has also happened with course events. Usually with events scheduled for one day and three days before. The task logs shows _fail_ in the result column.

**Expected behavior:**
Send a single email for each calendar event.

**Cron Logs:**
_Fail 1:_
Execute scheduled task: Recordatorios locales (local_reminders\task\send_reminders)
... started 00:00:12. Current memory use 37.3 MB.
   [Local Reminder] Time window: sábado, 23 de septiembre de 2023, 23:45 to domingo, 24 de septiembre de 2023, 00:00
   [Local Reminder] Found 2 upcoming events. Continuing...
   [Local Reminder] Processing event in ahead of 1 days.
   [Local Reminder] Processing event#46435 [Type: site, inaheadof=1 days]...
  [Local Reminder] Starting sending reminders for 46435 [type: site, mod: 0]
[LOCAL_REMINDERS] Mail Result: 2425275
[LOCAL_REMINDERS] Mail Result: 2425276
[LOCAL_REMINDERS] Mail Result: 2425277
[LOCAL_REMINDERS] Mail Result: 2425278
[LOCAL_REMINDERS] Mail Result: 2425279
[LOCAL_REMINDERS] Mail Result: 2425280
[LOCAL_REMINDERS] Mail Result: 2425281
[LOCAL_REMINDERS] Mail Result: 2425282
[LOCAL_REMINDERS] Mail Result: 2425283
[LOCAL_REMINDERS] Mail Result: 2425284
[LOCAL_REMINDERS] Mail Result: 
... used 94 dbqueries
... used 2.3224339485168 seconds
Scheduled task failed: Recordatorios locales (local_reminders\task\send_reminders),Object of class stdClass could not be converted to string

_Fail 2:_
Execute scheduled task: Recordatorios locales (local_reminders\task\send_reminders)
... started 00:02:02. Current memory use 23.9 MB.
Debugging increased temporarily due to faildelay of 60
   [Local Reminder] Time window: sábado, 23 de septiembre de 2023, 23:45 to domingo, 24 de septiembre de 2023, 00:02
   [Local Reminder] Found 2 upcoming events. Continuing...
   [Local Reminder] Processing event in ahead of 1 days.
   [Local Reminder] Processing event#46435 [Type: site, inaheadof=1 days]...
  [Local Reminder] Starting sending reminders for 46435 [type: site, mod: 0]
[LOCAL_REMINDERS] Mail Result: 2425286
[LOCAL_REMINDERS] Mail Result: 2425287
[LOCAL_REMINDERS] Mail Result: 2425288
[LOCAL_REMINDERS] Mail Result: 2425289
[LOCAL_REMINDERS] Mail Result: 2425290
[LOCAL_REMINDERS] Mail Result: 2425291
[LOCAL_REMINDERS] Mail Result: 2425292
[LOCAL_REMINDERS] Mail Result: 2425293
[LOCAL_REMINDERS] Mail Result: 2425294
[LOCAL_REMINDERS] Mail Result: 2425295
[LOCAL_REMINDERS] Mail Result: 
... used 97 dbqueries
... used 1.8762679100037 seconds
Scheduled task failed: Recordatorios locales (local_reminders\task\send_reminders),Object of class stdClass could not be converted to string
Backtrace:
* line 103 of /local/reminders/lib.php: call to local_reminders_cron_pre()
* line 48 of /local/reminders/classes/task/send_reminders.php: call to local_reminders_cron_task()
* line 259 of /lib/cronlib.php: call to local_reminders\task\send_reminders->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

Fail 3:
Execute scheduled task: Recordatorios locales (local_reminders\task\send_reminders)
... started 00:05:01. Current memory use 26.4 MB.
Debugging increased temporarily due to faildelay of 120
   [Local Reminder] Time window: sábado, 23 de septiembre de 2023, 23:45 to domingo, 24 de septiembre de 2023, 00:05
   [Local Reminder] Found 2 upcoming events. Continuing...
   [Local Reminder] Processing event in ahead of 1 days.
   [Local Reminder] Processing event#46435 [Type: site, inaheadof=1 days]...
  [Local Reminder] Starting sending reminders for 46435 [type: site, mod: 0]
[LOCAL_REMINDERS] Mail Result: 2425297
[LOCAL_REMINDERS] Mail Result: 2425298
[LOCAL_REMINDERS] Mail Result: 2425299
[LOCAL_REMINDERS] Mail Result: 2425300
[LOCAL_REMINDERS] Mail Result: 2425301
[LOCAL_REMINDERS] Mail Result: 2425302
[LOCAL_REMINDERS] Mail Result: 2425303
[LOCAL_REMINDERS] Mail Result: 2425304
[LOCAL_REMINDERS] Mail Result: 2425305
[LOCAL_REMINDERS] Mail Result: 2425306
[LOCAL_REMINDERS] Mail Result: 
... used 95 dbqueries
... used 2.0813148021698 seconds
Scheduled task failed: Recordatorios locales (local_reminders\task\send_reminders),Object of class stdClass could not be converted to string
Backtrace:
* line 103 of /local/reminders/lib.php: call to local_reminders_cron_pre()
* line 48 of /local/reminders/classes/task/send_reminders.php: call to local_reminders_cron_task()
* line 259 of /lib/cronlib.php: call to local_reminders\task\send_reminders->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

Fail 4:
Execute scheduled task: Recordatorios locales (local_reminders\task\send_reminders)
... started 00:10:02. Current memory use 41.7 MB.
Debugging increased temporarily due to faildelay of 240
   [Local Reminder] Time window: sábado, 23 de septiembre de 2023, 23:45 to domingo, 24 de septiembre de 2023, 00:10
   [Local Reminder] Found 2 upcoming events. Continuing...
   [Local Reminder] Processing event in ahead of 1 days.
   [Local Reminder] Processing event#46435 [Type: site, inaheadof=1 days]...
  [Local Reminder] Starting sending reminders for 46435 [type: site, mod: 0]
[LOCAL_REMINDERS] Mail Result: 2425308
[LOCAL_REMINDERS] Mail Result: 2425309
[LOCAL_REMINDERS] Mail Result: 2425310
[LOCAL_REMINDERS] Mail Result: 2425311
[LOCAL_REMINDERS] Mail Result: 2425312
[LOCAL_REMINDERS] Mail Result: 2425313
[LOCAL_REMINDERS] Mail Result: 2425314
[LOCAL_REMINDERS] Mail Result: 2425315
[LOCAL_REMINDERS] Mail Result: 2425316
[LOCAL_REMINDERS] Mail Result: 2425317
[LOCAL_REMINDERS] Mail Result: 
... used 95 dbqueries
... used 1.957533121109 seconds
Scheduled task failed: Recordatorios locales (local_reminders\task\send_reminders),Object of class stdClass could not be converted to string
Backtrace:
* line 103 of /local/reminders/lib.php: call to local_reminders_cron_pre()
* line 48 of /local/reminders/classes/task/send_reminders.php: call to local_reminders_cron_task()
* line 259 of /lib/cronlib.php: call to local_reminders\task\send_reminders->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

(Etc.)

**Environment:**
 - Moodle version: 4.1
 - Database: mysql
 - PHP Version: 8.0.30

**Additional context:**
Tested with versions 2.7 and 2.6 of the plugin

**Comment by isuru89** [comment]
@emilioferreiro 
I could not reproduce this issue. However, I looked at the last line in the backtrace you have presented here. 
Which in the code line 103 is empty in lib.php file. (https://github.com/isuru89/moodle-local_reminders/blob/master/lib.php#L103) 

Are you sure no one has changed the plugin files after downloaded and installed?

**Comment by emilioferreiro** [comment]
Hello, thank you for your reply. Yes, I am the Moodle administrator and I have access to the server, I have not modified the plugin in any way.

**Comment by isuru89** [comment]
I could not reproduce this, but I think I found the issue by looking at the code. I made a fix with latest version v2.7.1.

Please check and let me know.
