### ISSUE TITLE
Email reminders are sent for hidden assignments

### ISSUE THREAD

**Issue by hannibal001001** [isuru89/moodle-local_reminders#175]
Hello Isuru,

The email reminders are sent to the teachers and students even if the assignments still hidden.
Will be great if this bug will be fixed:-)

Best regards,

Valentin Green

**Environment (required):**
 - Moodle version: 4.1.6+
 - Plugin version: 2023110400
 - Database: mariadb
 - PHP Version: 7.4

**Comment by isuru89** [comment]
@hannibal001001 
Do you mean the `hidden` as the  'Availability' flag in common module settings?
If not, could you please add the reproducible steps, so that I can respond to the issue faster.

![image](https://github.com/isuru89/moodle-local_reminders/assets/1499404/f5a15857-247e-47da-b5f7-04302d391871)

**Comment by hannibal001001** [comment]
Hello Isuru,
Thank you for your quick answer. By hidden I mean a "hidden assignment for the students". For example, a course has been built in Aug 2023. The course has couple of assignments( with the correspondent "allow submission from", "due date", "cut-off date",... ). The first assignment has Oct 22 for "allow submission from", and Nov 03 for "due date". Until here nothing spectacular. At some moment we began to receive OVERDUE emails( both teachers and students ). And this seem to be the bug! For all kind of reasons, the course still "on hold", with the assignment set to "Hidden for students"!

**Comment by isuru89** [comment]
I tried to recreate the issue in below scenario, but all was unsuccessful. Overdue reminders were not sent when the course or the assignment is hidden. 

 1. Course is hidden for students  - Assignment from this course were visible on the Moodle calendar but No overdue reminders were sent.
![image](https://github.com/isuru89/moodle-local_reminders/assets/1499404/dc4bfbb1-995d-4a10-b3fc-d51cb4eb1c2d)

 2. Assignment made hidden on course page (as in my previous thread) - Assignment is hidden in Moodle calendar and no overdue emails were sent.

@hannibal001001 
I wonder, how did you made the course "on hold"? Doesn't it belong to either one of those above steps?

If not, could you please kindly provide an actual reproducible steps on how to create such a course and assignment and then task logs.

**Comment by hannibal001001** [comment]
@isuru89,
Please accept our apologizes. The problem was on our side( a deeply wrong usage of the hide-view property...).
About your question, well, it's hard to reproduce the events. A couple of Moodle 3.10 sites migrated to Moodle 4.1. And some courses get transferred too.  Here, on Moodle 4, a couple of courses were handled in a wrong manner...
Again, we're sorry for this "false alarm"
