### ISSUE TITLE
Plugin runs not on time

### ISSUE THREAD

**Issue by alinasamoilenko** [isuru89/moodle-local_reminders#179]
Hi!

We have a problem with the plugin. For some reason it only sends emails on the day of the assignment deadline at around 4-5 pm. And it still won't send reminders for all the activities scheduled. Here is what I found in the log:

Error: lib/moodlelib.php email_to_user(): SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingSMTP server error: QUIT command failed
Scheduled task failed: Local Reminders (local_reminders\task\send_reminders),Object of class stdClass could not be converted to string

We have Moodle version 4.2

Could you please help us solve it?

**Comment by isuru89** [comment]
@alinasamoilenko 
Could you please share the full logs related to the reminders part? So, I can investigate it.

**Comment by alinasamoilenko** [comment]
Sure. Here it is. @isuru89 
[local_reminders_task_send_reminders-42785800.log](https://github.com/isuru89/moodle-local_reminders/files/14824411/local_reminders_task_send_reminders-42785800.log)

**Comment by isuru89** [comment]
I fixed this via the latest release v2.7.2. Please kindly upgrade and let me know.

**Comment by alinasamoilenko** [comment]
@isuru89 Everything works correctly now. Thank you!
