### ISSUE TITLE
calendar event reminders and disabled users

### ISSUE THREAD

**Issue by chrisshearing** [isuru89/moodle-local_reminders#20]
We ran into an issue that crashed out the legacy cron task - it turned out a student in 2012 created a large number of calendar events which had dates in the future, the user has since left and been disabled but the calendar events are still present in the event table

The local_reminders cron task tried to retrieve the event information when iterating all the upcoming events, but crashed out on line 179 of /local/reminders/lib.php

`$event = new calendar_event($event);`

as the query for user context in calendar_event returned nothing when trying to find this users user_id and disabled=0

not sure if some error checking for a valid enabled user is supposed to be done before calling for a new calendar_event, or if this is a uncaught exception in the calendar_event  routine.

It should be reproducible by creating an event as a user and then disabling them.

**Comment by isuru89** [comment]
Will be released with plugin v2.3
