### ISSUE TITLE
Option to disable Event reminders for Big Blue Button meetings

### ISSUE THREAD

**Issue by davefoord** [isuru89/moodle-local_reminders#75]
There is currently an issue where the Big Blue Button plugin doesn't record its events in the standard format, which resulted in incorrect reminders going out to the wrong people. Update 2.2. to this plugin gives the option to turn off the big blue button event reminders on an event by event basis, but what would be ideal is the ability to either turn off all big blue button reminders at ideally course level or if this isn't possible, turn them off at site level.

**Comment by isuru89** [comment]
With a new exclusion filter at the site level (global), reminders can be disabled for desired modules starting from plugin v2.3
